# Site settings
title: Abhishek Dey
email:
description: "Training Deep Neural Networks from Scratch"
baseurl: ""
url: "https://deycoding.github.io"
github_username: deycoding

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
